from rest_framework import serializers
from .models import File

class FileSerializer(serializers.ModelSerializer):
    reference_count = serializers.SerializerMethodField()

    class Meta:
        model = File
        fields = [
            'id', 'file', 'original_filename', 'file_type', 'size', 'uploaded_at',
            'user_id', 'file_hash', 'is_reference', 'original_file', 'reference_count'
        ]
        # Fields that are truly generated by the database or serializer methods should be read-only.
        read_only_fields = ['id', 'uploaded_at', 'reference_count']
        extra_kwargs = {
            # 'file' is required for initial upload, but write_only (not shown in response)
            'file': {'write_only': True, 'required': True}
        }

    def get_reference_count(self, obj):
        if obj.is_reference and obj.original_file:
            source_file = obj.original_file
        else:
            source_file = obj
        
        if source_file:
            return source_file.references.count() + 1
        return 1
