# Generated by Django 4.2.21 on 2026-03-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file_type",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="file",
            name="size",
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="file",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["user_id", "file_type"], name="files_file_user_id_11f2e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["user_id", "size"], name="files_file_user_id_891e6c_idx"
            ),
        ),
    ]
